### ISSUE TITLE
something goes wrong in the step for "MetcalfScoring.setup preprocessing dataset"

### ISSUE THREAD

**Issue by AMao-0512** [NPLinker/nplinker#57]
Hi, Andrew,
I tried to use GNPS and Bigscape output data to be loaded into NPLinker for analysis, but an error was reported. Could you help to see it? 
--log--
Traceback (most recent call last):
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/server/contexts.py", line 173, in run_load_hook
    self._application.on_server_loaded(self.server_context)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/application/application.py", line 186, in on_server_loaded
    h.on_server_loaded(server_context)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/application/handlers/directory.py", line 232, in on_server_loaded
    return self._lifecycle_handler.on_server_loaded(server_context)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/bokeh/application/handlers/lifecycle.py", line 75, in on_server_loaded
    return self._on_server_loaded(server_context)
  File "/app/nplinker/webapp/npapp/server_lifecycle.py", line 58, in on_server_loaded
    nh.load()
  File "/app/nplinker/webapp/npapp/server_lifecycle.py", line 24, in load
    self.load_tables()
  File "/app/nplinker/webapp/npapp/server_lifecycle.py", line 47, in load_tables
    self.table_data.setup()
  File "/app/nplinker/webapp/npapp/tables_init.py", line 55, in setup
    metcalf_scoring = self.nh.nplinker.scoring_method('metcalf')
  File "/app/nplinker/webapp/npapp/../../prototype/nplinker/nplinker.py", line 546, in scoring_method
    self._scoring_methods[name].setup(self)
  File "/app/nplinker/webapp/npapp/../../prototype/nplinker/scoring/methods.py", line 468, in setup
    MetcalfScoring.DATALINKS.find_correlations(include_singletons=True)
  File "/app/nplinker/webapp/npapp/../../prototype/nplinker/scoring/data_linking.py", line 109, in find_correlations
    self.data_family_mapping(include_singletons=include_singletons)
  File "/app/nplinker/webapp/npapp/../../prototype/nplinker/scoring/data_linking.py", line 229, in data_family_mapping
    :] = self.M_spec_strain[np.where(self.mapping_spec["fam-id"][:, 0] == -1)[0], :]
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/pandas/core/series.py", line 906, in __getitem__
    return self._get_with(key)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/pandas/core/series.py", line 921, in _get_with
    return self._get_values_tuple(key)
  File "/app/conda/envs/bigscape/lib/python3.6/site-packages/pandas/core/series.py", line 956, in _get_values_tuple
    raise KeyError("key of type tuple not found and not a MultiIndex")
KeyError: 'key of type tuple not found and not a MultiIndex'

**Comment by andrewramsay** [comment]
I have never seen that particular error before... it looks like it might be something to do with a recent change I made to part of the Metcalf scoring code. 

I think the quickest way to check if this is the problem is for you to try running NPLinker again but using the previous version of the Docker image. 

To do this, run `docker pull andrewramsay/nplinker:v1.1.1` to download the image for the previous version. Then use the same command as normal to run NPLinker, but replace the `andrewramsay/nplinker` part with `andrewramsay/nplinker:v1.1.1` to tell it to use that specific version. 

Let me know if that works - if it does you should be able to keep using that version until I can find out what is wrong with the latest release.

**Comment by AMao-0512** [comment]
Using the previous version did fix the problem, and the program now works fine. Thank you very much for your help.

**Comment by AMao-0512** [comment]
Excuse me again, I ran into a problem again in the process of using the software.
'[WARNING] rosetta.py:278, Failed to match 3 BGCs to hits in directory *********. '
This warning appears in the RosettaScoring of each antismash folder. Is it true that no BGC will be compared to the output of GNPs? Because I did input the antismash results of matagenomic MAGs with the GNPS output data of the same sample. I tried several sets of sample data, but the results seem to be the same.
And end with ' [INFO] rosetta.py:292, Completed, 0 BGC hits found', '[WARNING] rosetta.py:403, Aborting Rosetta scoring data generation, no BGC hits were found!'.

**Comment by AMao-0512** [comment]
Excuse me again, I ran into a problem again in the process of using the software.
'[WARNING] rosetta.py:278, Failed to match 3 BGCs to hits in directory *********. '
This warning appears in the RosettaScoring of each antismash folder. 
And end with ' [INFO] rosetta.py:292, Completed, 0 BGC hits found', '[WARNING] rosetta.py:403, Aborting Rosetta scoring data generation, no BGC hits were found!'.
Is it true that no BGC can be compared to the output of GNPS? Because I did input the antismash results of matagenomic MAGs with the GNPS output data of the same sample. I tried several sets of sample data, but the results seem to be the same.

**Comment by andrewramsay** [comment]
For this to work it requires that you have knownclusterblast output files in your genomics data folder and they also have to be in a format that NPLinker can actually parse. 

There are currently 2 parsing methods that are attempted. The first one relies on being able to load the older text files generated by antiSMASH, the second one relies on loading the newer JSON files. If there are problems finding or parsing these files or they simply don't exist then you can have this problem (if you know Python the implementation is [here](https://github.com/sdrogers/nplinker/blob/8ee29cd1f12e2f03a64833dd28a9e00d8cf3cbd2/prototype/nplinker/scoring/rosetta/rosetta.py#L146)).

It might be helpful if you try running the app with full debugging output enabled. You can do that by editing your nplinker.toml file added a line at the top like this:

> loglevel = "DEBUG"

If there's already a "loglevel" line in the file just replace it with that one.

The extra log messages should provide a better indication of where the problem is.
